version: '3'

services:
  webapplication29:
    image: webapplication29:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapplication29$
    volumes:
      - C:\Users\salek\source\repos\WebApplication29\WebApplication29:/app
      - C:\Users\salek\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_webapplication29$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapplication29$ bin/Debug/netcoreapp2.0/WebApplication29.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
